export const GET_LIST_RECIPIENTS = 'GET_LIST_RECIPIENTS';
export const SUCCESS_LIST_RECIPIENTS = 'SUCCESS_LIST_RECIPIENTS';
export const GET_SUMMARY_RECIPIENT = 'GET_SUMMARY_RECIPIENT';
export const SUCCESS_SUMMARY_RECIPIENT = 'SUCCESS_SUMMARY_RECIPIENT';
export const GET_EVENTS_RECIPIENT = 'GET_EVENTS_RECIPIENT';
export const SUCCESS_EVENTS_RECIPIENT = 'SUCCESS_EVENTS_RECIPIENT';
export const FETCH_FAILED = 'FETCH_FAILED';
export const LOADING = 'LOADING';
