name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm ci 

      - name: Backend ESLint
        run: npm run eslint 
      - name: Backend Unit Tests
        run: npm run test:unit 
      - name: Backend Integration Tests
        run: npm run test:integration 
      - name: Backend Deployment
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./backend/*
          remote_path: /home/ubuntu/birdie/backend/
          remote_host: ec2-18-157-239-238.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.BIRDIE_SERVER_SSH_KEY }}"

