name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [18.x]

    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v3
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql ${{ env.DB_DATABASE }} -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < backend/dbseed/db.sql
      - run: npm ci --prefix backend

      - name: Backend ESLint
        run: npm run eslint --prefix backend
      - name: Backend Unit Tests
        run: npm run test:unit --prefix backend
      - name: Backend Integration Tests
        run: npm run test:integration --prefix backend
      - name: Backend Installing Dependencies
        run: npm ci --prefix backend
      - name: Backend Deployment
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./backend/*
          remote_path: /home/ubuntu/birdie/backend/
          remote_host: ec2-18-157-239-238.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.BIRDIE_SERVER_SSH_KEY }}"
